/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banko3rdterm;

import javax.swing.JOptionPane;

/**
 *
 * @author caria
 */
public class MainBank extends javax.swing.JFrame {

    /**
     * Creates new form MainBank
     */
    
    // Variable to store account balance
    private double accountBalance = 200000.0;
    
    
    public MainBank() {
        
        initComponents();
        this.jLabelBalance.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jBTrans = new javax.swing.JButton();
        jBWithdraw = new javax.swing.JButton();
        jBDeposit = new javax.swing.JButton();
        jLabelBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel5.setLayout(null);

        jBTrans.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jBTrans.setText("Transfer Money");
        jBTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTransActionPerformed(evt);
            }
        });
        jPanel5.add(jBTrans);
        jBTrans.setBounds(410, 140, 150, 50);

        jBWithdraw.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jBWithdraw.setText("Withdraw");
        jBWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBWithdrawActionPerformed(evt);
            }
        });
        jPanel5.add(jBWithdraw);
        jBWithdraw.setBounds(20, 140, 150, 50);

        jBDeposit.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jBDeposit.setText("Deposit");
        jBDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDepositActionPerformed(evt);
            }
        });
        jPanel5.add(jBDeposit);
        jBDeposit.setBounds(220, 140, 150, 50);

        jLabelBalance.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel5.add(jLabelBalance);
        jLabelBalance.setBounds(150, 40, 320, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTransActionPerformed
        // TODO add your handling code here:
        double amountToTransfer = Double.parseDouble(JOptionPane.showInputDialog("Enter amount to transfer:"));
        if (amountToTransfer <= accountBalance) {
            accountBalance -= amountToTransfer;
            updateBalanceLabel();
            JOptionPane.showMessageDialog(null, "Transfer successful!");
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient funds!");
        }
        
    }//GEN-LAST:event_jBTransActionPerformed

    private void jBDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDepositActionPerformed
        // TODO add your handling code here:
        
        double amountToDeposit = Double.parseDouble(JOptionPane.showInputDialog("Enter amount to deposit:"));
        if (amountToDeposit > 0) {
            accountBalance += amountToDeposit;
            updateBalanceLabel();
            JOptionPane.showMessageDialog(null, "Deposit successful!");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid amount!");
        }
        
    }//GEN-LAST:event_jBDepositActionPerformed

    private void jBWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBWithdrawActionPerformed
        // TODO add your handling code here:
        
        double amountToWithdraw = Double.parseDouble(JOptionPane.showInputDialog("Enter amount to withdraw:"));
        if (amountToWithdraw <= accountBalance && amountToWithdraw > 0) {
            accountBalance -= amountToWithdraw;
            updateBalanceLabel();
            JOptionPane.showMessageDialog(null, "Withdrawal successful!");
        } else if (amountToWithdraw <= 0) {
            JOptionPane.showMessageDialog(null, "Invalid amount!");
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient funds!");
        }
        
    }//GEN-LAST:event_jBWithdrawActionPerformed

    private void updateBalanceLabel() {
        jLabelBalance.setText("Account Balance: $" + accountBalance);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDeposit;
    private javax.swing.JButton jBTrans;
    private javax.swing.JButton jBWithdraw;
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
